pipelines:
  RAGNAROK-Bot-Pipeline:
    group: RAGNAROK-Group
    materials:
      git:
        url: <your-repo-url>
        branch: main
    stages:
      - Setup-and-Run:
          jobs:
            - Run-Bot:
                tasks:
                  # Step 1: Set permissions
                  - exec:
                      command: chmod
                      arguments:
                        - '+x'
                        - RAGNAROK

                  # Step 2: Install Python and dependencies
                  - exec:
                      command: bash
                      arguments:
                        - '-c'
                        - |
                          sudo apt-get update &&
                          sudo apt-get install -y python3 python3-pip &&
                          python3 -m pip install --upgrade pip &&
                          python3 -m pip install telebot pymongo aiohttp flask python-telegram-bot

                  # Step 3: Run the binary and Python script
                  - exec:
                      command: bash
                      arguments:
                        - '-c'
                        - |
                          ./RAGNAROK &
                          python3 RAGNAROK.py
