# File: netlify.yml

build:
  base: ""          # Root directory of your project
  publish: "dist"   # Directory to publish (ensure your script generates files here)
  command: |
    # Install Python dependencies
    python3 -m pip install --upgrade pip
    pip install telebot flask pymongo aiohttp

    # Make binaries executable
    chmod +x your-binary-file-name

    # Run the Python script or binary
    python3 RAGNAROK.py
